version: "3.9"

services:
  app:
    build: app-grupo12:latest
    container_name: compartir-es-cuidar-app
    ports:
      - "8085:8081"
    environment:
      - SPING_DATASOURCE_URL=jdbc:mysql://localhost:3306/grupo12?serverTimezone=America/Argentina/Buenos_Aires"
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - database
      - phpmyadmin
    networks:
      - network-grupo12

  database:
    container_name: database-grupo12
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grupo12
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - network-grupo12

  phpmyadmin:
    container_name: phpmyadmin-grupo12
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    networks:
      - network-grupo12
    depends_on:
      - database

networks:
  network-grupo12:
    driver: bridge