# Generated by Django 5.1.1 on 2024-09-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('altura', models.PositiveIntegerField()),
                ('codigo_postal', models.PositiveIntegerField()),
                ('localidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='app_atencion_medica.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaVulnerable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('PAS', 'Pasaporte'), ('LIC', 'Licencia de conducir')], max_length=20, null=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerables', to='app_atencion_medica.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVianda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('localidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app_atencion_medica.localidad')),
                ('persona_vulnerable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app_atencion_medica.personavulnerable')),
            ],
        ),
    ]
