# Generated by Django 5.1.1 on 2024-09-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_atencion_medica', '0002_remove_personavulnerable_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personavulnerable',
            name='tipo_documento',
        ),
    ]
