# Generated by Django 5.1.1 on 2024-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_atencion_medica', '0003_remove_personavulnerable_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='personavulnerable',
            name='apellido',
            field=models.CharField(default='', max_length=200),
        ),
    ]
