# Generated by Django 5.1.1 on 2024-09-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_atencion_medica', '0004_personavulnerable_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudvianda',
            old_name='persona_vulnerable',
            new_name='persona_vulnerable_id',
        ),
    ]
