# Generated by Django 5.1.1 on 2024-09-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_atencion_medica', '0005_rename_persona_vulnerable_solicitudvianda_persona_vulnerable_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudvianda',
            old_name='localidad_id',
            new_name='localidad',
        ),
    ]
