# Generated by Django 5.1.1 on 2024-09-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_atencion_medica', '0006_rename_localidad_id_solicitudvianda_localidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudvianda',
            name='persona_vulnerable_id',
        ),
        migrations.AddField(
            model_name='solicitudvianda',
            name='persona_vulnerable',
            field=models.ForeignKey(db_column='persona_vulnerable_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app_atencion_medica.personavulnerable'),
        ),
        migrations.AlterField(
            model_name='personavulnerable',
            name='localidad',
            field=models.ForeignKey(db_column='localidad_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerables', to='app_atencion_medica.localidad'),
        ),
        migrations.AlterField(
            model_name='solicitudvianda',
            name='localidad',
            field=models.ForeignKey(db_column='localidad_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app_atencion_medica.localidad'),
        ),
    ]
